# small sample
#data_input: '/Users/shiran.s/dev/p300_net/data/IIb/test_loading_code'
#data_output: '/Users/shiran.s/dev/p300_net/output/processed_data/small/'

# all data
data_input: '/Users/shiran.s/dev/p300_net/data/IIb'
data_output: '/Users/shiran.s/dev/p300_net/output/processed_data_six_channels_3/'
